name: Build
env:
  ZENDESK_USERNAME: "email@example.com"
  ZENDESK_API_KEY: "some-fake-api-key"
  OPSGENIE_API_KEY: "some-fake-api-key"
  FIRST_LINE_DEV_SUPPORT_GROUP_ID: 444111
  OPSGENIE_SCHEDULE_ID: "e71d500f-896a-4b28-8b08-3bfe56e1ed76"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        script/test
