name: Build
env:
  ZENDESK_USERNAME: "email@example.com"
  ZENDESK_API_KEY: "some-fake-api-key"
  OPSGENIE_API_KEY: "some-fake-api-key"
  FIRST_LINE_DEV_SUPPORT_GROUP_ID: 444111
  OPSGENIE_SCHEDULE_ID: "e71d500f-896a-4b28-8b08-3bfe56e1ed76"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path ./vendor/bundle
    - name: Build and test with Rake
      run: script/test
