name: Run
env:
  ZENDESK_API_URL: ${{ secrets.ZENDESK_API_URL }}
  ZENDESK_USERNAME: ${{ secrets.ZENDESK_USERNAME }}
  ZENDESK_API_KEY: ${{ secrets.ZENDESK_API_KEY }}
  OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}

on:
  schedule:
    - cron: '0 6 * * 1-5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Assign current support user to correct group
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake huntaway:run
