name: Unassign outgoing support user
env:
  ZENDESK_API_URL: ${{ secrets.ZENDESK_API_URL }}
  ZENDESK_USERNAME: ${{ secrets.ZENDESK_USERNAME }}
  ZENDESK_API_KEY: ${{ secrets.ZENDESK_API_KEY }}
  OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
  FIRST_LINE_DEV_SUPPORT_GROUP_ID: 21306177
  OPSGENIE_SCHEDULE_ID: "e71d500f-896a-4b28-8b08-3bfe56e1ed76"

on:
  schedule:
    - cron: '0 15 * * MON-FRI'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path ./vendor/bundle
    - name: Unassign outgoing support user from the first line support group
      run: bundle exec rake huntaway:unassign_extra_users_from_group
